version: '2'

services:
#  prometheus:
#    image: prom/prometheus
#    ports:
#      - 9090:9090
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#  grafana:
#    image: grafana/grafana
#    ports:
#      - 3000:3000
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=password
#    volumes:
#      - $PWD/extra/grafana_db:/var/lib/grafana grafana/grafana

  consul:
    image: progrium/consul:latest
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53/udp
    hostname: consulserver
    command: -server -bootstrap -ui-dir /ui

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411